# fly.toml app configuration file generated for gitchess on 2026-09-13T23:12:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitchess'
primary_region = 'yyz'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[env]
  GITCHESS_HOST = '0.0.0.0'
  GITCHESS_HOST_KEY = '/data/ssh_host_ed25519'
  GITCHESS_PORT = '2222'
  GITCHESS_REPO = '/data/chess.git'
  GITCHESS_WEB_HOST = '0.0.0.0'
  GITCHESS_WEB_PORT = '8080'

[[mounts]]
  source = 'gitchess_data'
  destination = '/data'
  initial_size = '1gb'
  snapshot_retention = 14

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 22

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ['http']
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
